### ISSUE TITLE
[request] customize version name output format

### ISSUE THREAD

**Issue by wrozwad** [gladed/gradle-android-git-version#20]
I'm lazy (as many devs :wink: ) and I want to versioning my app in such format `1.2.34`
- `1` - just digit as many others
- `2` - number of sprint
- `34` - number of commits since last tag

As you can see I want to:
- change _number of commits since tag_ from dash to dot: `-%d` to `.%d`
- avoid display _commit checksum_
- in some cases even avoid `dirty` flag

All of above could be defined in androidGitVersion settings, eg:

```
androidGitVersion {
    commitsSinceTagPrefix .
    commitChecksumVisible false
    dirtyVisible false
}
```

**Comment by GladeDiviney** [comment]
How about something like this:

```
androidGitVersion {
    format = '%tag%%-count%%-commit%%-branch%%-dirty%'
}
```

Then you could decide which parts you want, which parts to hide, what order they are in, and what separator to use if that part is present.

I think we would still hide parts that weren't relevant, like a hidden branch, or a build from a tag with no subsequent commits.

**Comment by GladeDiviney** [comment]
This is present in fd7c528 (version 0.2.18)

**Comment by wrozwad** [comment]
Looks great, thx! :+1:
