### ISSUE TITLE
Ancestroy Tags missing on develop/feature/release branches when using GitFlow

### ISSUE THREAD

**Issue by brianwallace** [gladed/gradle-android-git-version#22]
Do you have any guidance for using this plugin when using the gitflow branching model?  Since tags are placed on `master` when using gitflow, there is no tag ancestor of the development branch in many cases which means `git describe --tags --dirty` is not super helpful when development or feature branches.

Here are some of the relevant GitFlow issues:
- https://github.com/nvie/gitflow/pull/179
- https://github.com/nvie/gitflow/issues/126

**Comment by brianwallace** [comment]
Note: I was able to work around the git-flow limitation by merging `master` into `develop` so that the tag ancestry was developed.

```
git fetch
git checkout develop
git merge master
```

Still wondering if there are any other "best practices" that I could apply when using git-flow.  If not, feel free to close this issue.

**Comment by gladed** [comment]
Best practice: http://endoflineblog.com/gitflow-considered-harmful :smile: 

But seriously I'm glad you found a workaround. "Vanilla" git-flow doesn't have the tag in the necessary commit histories, as you observed, and I think your workaround is good.

**Comment by GladeDiviney** [comment]
I've been thinking more about this and I think, whether you're using git-flow or not, that a "mergeback" from your release branch into your master is a good idea.

In some cases, people make "hotfixes" to the release branch, and those need to be merged back into the mainline development branch anyhow. Once you've done this, android-git-version will be able to reach the most recent tagged commit, and will give you good version names.

Another way to do it is to tag your develop branch with the next version code pre-emptively.

For example:

```
develop: a --> b --> d (1.1-dev) ---------> f 
master:         \--> c (1.0) --> e (1.0.1)   \--> g (1.1)
```

Commit `f` will be called `1.1-dev-1` or something like it.

**Comment by rpmsmacedo** [comment]
I know this is quite old, but I'm hitting this problem right now.

Taking into account a similar case as the one described:
```
develop: a --> b --> d (1.1) -----------------m--> f 
master:         \--> c (1.0) --> e (1.0.1) --/      \--> g (1.1)
```
If there's a merge from master back to develop, then on commit `f` will be named `1.0`, however using `git describe` the result is `1.1`.

Is this the expected behaviour? If it is do you have any kind of workaround - besides a new tag on develop?

**Comment by gladed** [comment]
The best solution I have is [`tagPattern`](https://github.com/gladed/gradle-android-git-version/blob/master/README.md#tagpattern-stringregex). It does require that on your master's `build.gradle` you modify the `tagPattern` once per major release.

Open to other ideas if anyone has them; it's a fundamental git limitation that the branch doesn't remember which commits it _used to be on_, only the commit it's on at the present time.
