### ISSUE TITLE
Incorrect versionCode and tag name

### ISSUE THREAD

**Issue by TamasBarta** [gladed/gradle-android-git-version#28]
I'm getting this output from the terminal (I hope it has all the info you need):

```
[tamas@tamas-antergos]$ git describe 
v0.7
[tamas@tamas-antergos]$ gradle --quiet androidGitVersion
androidGitVersion.name  untagged-49-fdfd1cd-fdfd1cd940cffb5fc2fe5d6488b90e38b56585f7-dirty
androidGitVersion.code  0
[tamas@tamas-antergos]$ ./gradlew --version

------------------------------------------------------------
Gradle 2.14.1
------------------------------------------------------------

Build time:   2016-07-18 06:38:37 UTC
Revision:     d9e2113d9fb05a5caabba61798bdb8dfdca83719

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_92 (Oracle Corporation 25.92-b14)
OS:           Linux 4.8.2-1-ARCH amd64
```

Tried with light, annotated, and signed tags, with same results.

**Comment by gladed** [comment]
It's the `v` in `v0.7`. You can either tag without the `v`, or add `prefix='v'` to your `androidGitVersion` settings.

**Comment by TamasBarta** [comment]
Wow, thanks for the super fast reaction, and sorry for the confusion (and improper reading of your documentation).

**Comment by gladed** [comment]
Not a problem! Let me know if you run into anything else.

**Comment by AllanWang** [comment]
I seem to have the same issue even with the prefix 'v' added under the settings. Any idea what the issue might be?

**Comment by AllanWang** [comment]
I would also like to note for those who might also have this issue that the `androidGitVersion` settings need to be placed before the build configs, otherwise they won't be read on time.

**Comment by gladed** [comment]
Thanks for the note. I've added special mention of this in the readme.
