### ISSUE TITLE
untracked files not committed not considered 'dirty'.  Intentional?

### ISSUE THREAD

**Issue by dlethin** [gladed/gradle-android-git-version#29]
Great plugin, and I was hoping to convince my team to switch over to using it.  I was working on a quick demo to show how easy it was and ran into an edge case where I don't think it works correctly.

Here is the scenario --  I've added a file I intend to check in but haven't yet.

```
$ git status
On branch develop2
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	pretend_bug_fix.java

nothing added to commit but untracked files present (use "git add" to track)
```

Since my I have locally uncommitted changes, I would think that my version name would include the 'dirty' suffix, but it does not:

```
$ ./gradlew androidGitVersion
:androidGitVersion
androidGitVersion.name  2.1.1
androidGitVersion.code  20101
```

It's only if I actually mark the the file for add that dirty works.

```
$ git add pretend_bug_fix.java 
$ ./gradlew androidGitVersion
:androidGitVersion
androidGitVersion.name  2.1.1-dirty
androidGitVersion.code  20101
```

Is this intentional?   Is there a way to make this support optional in the plugin configuration?

Thanks.

**Comment by gladed** [comment]
The formal definition of git dirty is here: https://www.kernel.org/pub/software/scm/git/docs/gitglossary.html#def_dirty

What you have here is an _untracked file_. Same thing as a log file in the home directory or a build folder that isn't listed in `.gitignore`.

It would be possible to have something like `untrackedIsDirty true` perhaps (although it seems very strict to me!) Would this meet your needs?

**Comment by dlethin** [comment]
Yes, perhaps its a bit of an edge-case and quite honestly something we could easily live without.  I only came across it while evaluating the tool and it was the quickest way I could think of to demonstrate simulating a bug fix and watching what happens to the version name and was surprised  when it didn't change.  Your explanation makes sense.

Your solution sounds like it would work fine with the current behavior acting as the default but allowing a more strict usage via a simple config change if needed.  

That being said, now that I've thought through it, this is not a blocker for us, and its probably not the hugest priority. I was coming at this from the perspective of revamping our whole release process and was more thinking that I don't want to publish/release the project if the git workspace has dirty or untracked files, and we could use this plugin to determine that, but perhaps I'm conflating the two concerns and there are other gradle plugins that can help us here.

Thanks.

**Comment by gladed** [comment]
Feature is in now, if you choose to use it :)
