### ISSUE TITLE
Add possibility to set codeFormat to year, month, day, hour and minute

### ISSUE THREAD

**Issue by odin-** [gladed/gradle-android-git-version#32]
It would be great if it was possible to set codeFormat to year, month, day, hour or minute. I would prefer an autoincremental versionCode instead of a one based on git commits.

**Comment by gladed** [comment]
Good idea. By time of last commit?

**Comment by odin-** [comment]
No, rather the current time when I exported the APK. 

The reasoning is that I might upload "betas" (dirty/amended commits) to Google Play Developer Console. Thus if only using version or commit count (B) the versionCode would never increment but Google Play Developer Console would still want me to increase the versionCode. 

If we used the exported date I would always have a "new" versionCode number.

Tried to add it myself but I didn't understand how to use my local compiled version of your plugin :-)

**Comment by gladed** [comment]
Well...a couple things give me pause:
- I think it is generally safer to push releases from commits, so you always have a record of what is in the playstore. 
- I also think in general that "build time" doesn't tell you as much as "last commit". If I build from the same bits, I should get the same result...[no snowflakes!](https://martinfowler.com/bliki/SnowflakeServer.html)
- The number of digits available in the `versionCode` is not sufficient to store a *full* date stamp unless you toss most or all of the version number ... in which case this plugin probably isn't going to help a ton.

That said, I'm not trying to dictate your build pipeline -- it's yours to decide!

So: I created an `X` code and pushed this into 0.3.1. This just leaves a 0 which you can fill as you wish by amending `baseCode`. Sound good?

**Comment by odin-** [comment]
I agree it's safer to push from commits. But let's say I have SW in the beta tab in Google Play Developer Console. Then creating new commits per upload just to step the versionCode (and you need to step the versionCode each time a APK is uploaded) doesn't feel right because perhaps I just want to amend the previous commit. I.e. if I just keep amending based on the comments from my beta testers the versionCode doesn't get increased. 

So I want to have some kind of auto increment to be able to push amended commits to the beta section in GPDC.

Any ideas about this?

**Comment by gladed** [comment]
YMMV, but in my experience a build that other people see deserves its own commit. In the future looking back to see the changes for each beta iteration could have some value. For example, you could change your mind and revert on a single commit. You can't do that if the commit has lots of changes rolled up into it.

But if amending is your workflow, you can also keep adding tags to the same commit to set the version name/code you want to expose. The plugin will always take the latest one, so if a commit has 1.2.345 and 1.2.346 it will take 1.2.346 for the name and code. This would give you the advantage of asking a beta user which one they were on, and you could at least tell they weren't on the latest!

And with the X digit in baseCode you can also try inserting your own clock-based designator into the baseCode if that's what you want to do.

Good luck!

**Comment by odin-** [comment]
OK thank you for your input and the change you did for me!

/ Henrik
