### ISSUE TITLE
SplitAPK Support?

### ISSUE THREAD

**Issue by eikaramba** [gladed/gradle-android-git-version#33]
Currently it seems splitapk is not supported, as we get the same versioncode for every platform. But this should be different like e.g. 9031002 for x64 3031002 for arm64

**Comment by eikaramba** [comment]
btw adding this could be fairly easy. basically there is a fixed schema from google, that every developer needs to follow. therefore this plugins would need to just add the platform number to the start of the versioncode.
see https://gist.github.com/ph0b/69586260bc20c58136ef

**Comment by gladed** [comment]
You can probably fake this right now with `baseCode` and `formatCode` with the `X` digit (or updating formatCode manually after the fact). But it would be much nicer to have a digit like `S`, which takes from a platform code.

@eikaramba do you know of a way to get a canonical digit for the platforms listed at https://developer.android.com/ndk/guides/abis.html? The link specifies one but is it arbitrary?

Also it's possible in the future they could have more than 10 and one digit wouldn't be enough.

**Comment by eikaramba** [comment]
The gist that i linked (which we basically also use) is providing a way for this. There is no automatic way to get the digit, because there is none. Everyone can define this as he wants to. Only by using a mapping between platform names and codes, we can achive to define a list of digits and then automatically use that for the versioncode. You can see here(https://androidbycode.wordpress.com/2015/06/30/android-ndk-version-code-scheme-for-publishing-apks-per-architecture/) an example that is widely used as a schema.

I think you are right, double digits are possible and so it should be SSMMMNNNPPP.

One question: How can i adjust the baseCode or formatCode dynamically, let's say in this piece of code?
There we currently overwrite the versioncode. But this does not work anymore after switching to your plugin. Now the versioncode stays the same. 
```
android {
.....
project.ext.versionCodes = ['armeabi': 1, 'armeabi-v7a': 2, 'arm64-v8a': 3, 'mips': 5, 'mips64': 6, 'x86': 8, 'x86_64': 9]
applicationVariants.all { variant ->
        variant.outputs.each { output ->
            output.versionCodeOverride = project.ext.versionCodes.get(output.getFilter(com.android.build.OutputFile.ABI), 0) * 1000000 + android.defaultConfig.versionCode
            def outputFile = output.outputFile
            if (outputFile != null && outputFile.name.endsWith('.apk')) {
                def fileName = project.ext.versionCodes.get(output.getFilter(com.android.build.OutputFile.ABI), 0) + '-' + outputFile.name.replace('.apk', "-${getVersionCode()}.apk")
                try {
                    output.outputFile = new File(outputFile.parent, fileName)
                } catch (ex) {
                    printf("small problem for renaming : " + ex)
                }
            }
        }
    }
....
}
```

**Comment by gladed** [comment]
Thanks, very helpful!

`android.defaultConfig` is only processed once. So something like `androidGitVersion.handleVariants(applicationVariants)` will be necessary.

If I let the user define the mapping (probably they already have a mapping) then it can just be passed in as a config to `androidGitVersion { }`

**Comment by eikaramba** [comment]
exactly, i also thought about this. just put it into the config and then everyone can decide how to map the versioncodes for the platform.

BTW: i tried `androidGitVersion.baseCode = project.ext.versionCodes.get(output.getFilter(com.android.build.OutputFile.ABI), 0) * 1000000` in the above code to dynamically set the baseCode but it didn't worked. I don't groovy so much and how android plugins work, maybe there is a way to make it work. otherwise we need to wait for the mapping option :) Thanks nevertheless for the really quick answers. Appreciate it. hopefully we can soon use it in our production app.

**Comment by gladed** [comment]
If you set `android.defaultConfig.versionCode`, then change the `baseCode`, it won't have any direct effect since `versionCode` already been calculated and assigned.

Might be easier to just do `output.versionCodeOverride = [...] + android.defaultConfig.versionCode` like you are doing in your earlier snippet, which should work fine.

**Comment by gladed** [comment]
Thank YOU for giving feedback -- it makes a better plugin for everyone :)

**Comment by eikaramba** [comment]
touché, however unfortunately the above snippet does not work with your plugin. i don't know why but the versionCode is always the same, i mean for every platform. Before it was working fine. I will try to debug it more.

**Comment by gladed** [comment]
@eikaramba try 0.3.3, take care to note the requirements [here](https://github.com/gladed/gradle-android-git-version#codeformat-string).

With this feature you shouldn't need to change `output.versionCodeOverride` or `baseCode`. You may still need `applicationVariants.all` if you want to mess without output names of course.

Let me know if it works!

**Comment by eikaramba** [comment]
it works! thank you. the only downside is that within the applicationVariants loop the output from `getVersionCode()` is always the same and does not involve the API platform. i can live with that, as this is just a naming thing. the actual versioncode inside the apk is correct.

**Comment by gladed** [comment]
Thanks for trying it out @eikaramba, and I'm glad it worked!

`androidGitVersion.code()` can only return the generic `versionCode`, because it doesn't know what ABI is being targeted for the current "output". The correct one should (I hope?) already be in `output.versionCodeOverride` if you need to reuse it for something else or modify it further.

**Comment by eikaramba** [comment]
and you are right again, now everything's perfect :) thx
