### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by hrydgard** [gladed/gradle-android-git-version#35]
When using this plugin (which is great btw!) gradle 3.3 emits the following warning:

    The Task.leftShift(Closure) method has been deprecated and is scheduled to be removed in Gradle 5.0.
    Please use Task.doLast(Action) instead.

Still plenty of time before Gradle 5.0, but would be good to fix.

**Comment by GladeDiviney** [comment]
Yes, this is ugly. Will fix.

**Comment by gladed** [comment]
Fixed in `0.3.4`, thanks for reporting it!

**Comment by hrydgard** [comment]
Okay, so using 0.3.4 seems to work but version names got a lot longer if they include git hashes, they now seem to include the full hash? Anyway, the latest change I see in the git repo is 28 days old, how come when this fix can at most be 4 days old?

**Comment by gladed** [comment]
Hm, the fix is in  35fb823 but it's not showing on the front page, I must not have pushed the branch :)

Commit tags should be the same as in prior versions...can you post your `gradle androidGitVersion` results?

**Comment by hrydgard** [comment]
gradle androidGitVersion shows a normal 1.4-20 (for example) but when I build from Jenkins using assembleRelease I get the full commit hash included, curiously. Not sure what's going on...

**Comment by hrydgard** [comment]
gradle code:

	androidGitVersion {
		codeFormat = "MNPPBBBB"
		format = "%tag%%-count%%-branch%%-dirty%"
		prefix = "v"  // Only tags beginning with v are considered.
	}

	defaultConfig {
		applicationId 'org.ppsspp.ppsspp'
		println "Overriding Android Version Name, Code: " + androidGitVersion.name() + " " + androidGitVersion.code();
		versionName androidGitVersion.name()
		versionCode androidGitVersion.code()

Logs:

	Overriding Android Version Name, Code: 1.4-20-8244b8246bcd9b7826eb56ad85942376d086b034 14000020

when doing assembleRelease, but

	gradlew androidGitVersion
	Overriding Android Version Name, Code: 1.4-20 14000020
	Incremental java compilation is an incubating feature.
	C:\dev\ppsspp\assets
	:android:androidGitVersion
	androidGitVersion.name  1.4-20
	androidGitVersion.code  14000020

when doing gradlew androidGitVersion.

**Comment by gladed** [comment]
Is Jenkins building from its own local branch?

**Comment by hrydgard** [comment]
Oh, sorry, yes indeed it is, the Jenkins git plugin is doing a bunch of weirdness. False alarm! Again, sorry for wasting your time.

**Comment by gladed** [comment]
No problem!
