### ISSUE TITLE
Need to sync gradle after every commit

### ISSUE THREAD

**Issue by 0neel** [gladed/gradle-android-git-version#37]
Hello!
Your plugin is cool, but I have an issue.

Every time I commit changes Android Studio starts failing apk installation.
It prints a message like this:

The APK file path/to/app-PREVIOUS_COMMIT_VERSION_INFO.apk does not exist on disk.

Or it just installs the previously built apk.
I have to perform Gradle sync to fix this. And it's very annoying.

Tried to add something like this to my build.gradle, but it didn't help:
```
task flushGitInfo {
    android.applicationVariants.all { variant ->
        variant.assemble.doFirst {
            androidGitVersion.flush()
        }
    }
}
```

So is it possible to do something to avoid Gradle synchronization?

**Comment by GladeDiviney** [comment]
Not sure this is related to the plugin...have you tried https://stackoverflow.com/questions/34039834/the-apk-file-does-not-exist-on-disk?

**Comment by 0neel** [comment]
Will check this on Monday

**Comment by 0neel** [comment]
Checked some answers, none of them helped. Looks like it's connected only with Android Studio and file name generation. So, I'm closing the issue. Thanks

**Comment by gladed** [comment]
Just a quick note on this -- in several cases I've tried to alter the name of the APK built by Gradle and it always causes trouble. The best results seem to come with adding Gradle tasks or bash scripts to make a separate copy of the APK containing the version name.

**Comment by 0neel** [comment]
Yeah, looks like these are easiest ways. And it's quite sad
