### ISSUE TITLE
Feature: Option to add commit count to baseCode

### ISSUE THREAD

**Issue by AllanWang** [gladed/gradle-android-git-version#40]
It would be nice if we could have a function that could add on the number of commits to the baseCode as a way of auto incrementing the versions.

Something like:

```gradle
ext.commitCount = { ->
    def repo
    def count = 0
    try {
        repo = new FileRepositoryBuilder()
                .readEnvironment()
                .findGitDir(project.projectDir)
                .build()
    } catch (IllegalArgumentException ignore) {
        // No repo found
        return count
    }

    def git = Git.wrap(repo)
    def commits = git.log().call()
    return commits.size()
}
```

combine this with MMNNPPXX and it will enable constant updates.

**Comment by gladed** [comment]
You can already do `MMNNPPBB` to get two digits for the number of commits since the last tag. Does that work?

**Comment by AllanWang** [comment]
My bad. I didn't notice that in the readme. I'll try that.

**Comment by gladed** [comment]
Cool, good luck!
