### ISSUE TITLE
Does the library fall back if git is not present?

### ISSUE THREAD

**Issue by timusus** [gladed/gradle-android-git-version#45]
Just a couple of questions, not really an issue with this library, but I'm wondering if you can help me out.

1.) ~What happens if the user doesn't have git installed/available on their PATH? Does it just fall back to the base version code? I'm asking because this is one of the issues with my own implementation of git versioning (a very simplistic version), and one of the reasons I'm looking at your library.~

Edit: I realise now that JGit is being used, so command line Git is not required. 

2.) My naive implementation looks like this:

```groovy
def gitCommitCount() {
    def commitCount = 0
    try {
        def stdout = new ByteArrayOutputStream()
        exec {
            commandLine 'git', 'rev-list', '--all', '--count'
            standardOutput stdout
        }
        commitCount = stdout.toString().trim().toInteger()
    }
    catch (error) {
        println "Error: ${error}"
    }
    return commitCount
}
```

When I try to generate a build with my continuous deployment tool (travis), often the versionCode comes out to be lower than the previous build's versionCode. I think this has something to do with tagging/branching affecting the count, but I don't understand git well enough to figure out why.

You seem familiar with git, and I imagine you've probably come across similar issues. Just wondering if you could help me understand where I'm going wrong?

**Comment by gladed** [comment]
Yup, `git` is not required!

CI servers, including Travis, will pull "shallow" clones to save on bandwidth. To prevent this you can exec `git fetch --unshallow` or [configure the depth in `.travis.yml`](https://docs.travis-ci.com/user/customizing-the-build/#Git-Clone-Depth).
