### ISSUE TITLE
How to use for a project with multiple submodules?

### ISSUE THREAD

**Issue by AllanWang** [gladed/gradle-android-git-version#46]
May be more of a gradle question.

I've seen from #21, that this is supported, but what's the best way of importing the plugin for each submodule?

The current way:

```gradle
plugins {
    id 'com.gladed.androidgitversion' version '0.4.3'
}
```

Seems to only work if it's done directly in the app `build.gradle`, meaning that it needs to be copied each time, and I presume it will need to check for the tags individually each time. Instead, it may be better for me to simply import it once, and get the tags to use for each submodule. I'm not entirely sure how to do that though, so any help would be great.

**Comment by gladed** [comment]
Generally each project stands alone with regard to git tags. Meaning, git submodules can have their own tags, but this doesn't affect the parent project. And this plugin only looks for the git state of the current project's `projectDir`.

Can you give me a little more info about your use case? Maybe there's a workaround or missing plugin feature to support it.

**Comment by AllanWang** [comment]
My project is [here](https://github.com/AllanWang/KAU).

Essentially, every submodule calls for the git name and code, and the tag is for the entire project. I think the issue I had before was trying to import the plugin properly in the main build gradle, as the plugin line needs to be at the top with that format.

**Comment by gladed** [comment]
Oh, I understood "submodule" to mean "git submodule". Here you just have gradle subprojects. Your question makes more sense to me now :)

To solve this you can follow the first style currently shown at https://plugins.gradle.org/plugin/com.gladed.androidgitversion:

```
buildscript {
  repositories {
    maven {
      url "https://plugins.gradle.org/m2/"
    }
  }
  dependencies {
    classpath "gradle.plugin.com.gladed.gradle.androidgitversion:gradle-android-git-version:0.4.3"
  }
}

[...]

subprojects {
  apply plugin: 'com.gladed.androidgitversion'
  [...]
}
```

Then all of your gradle subprojects receive the plugin automatically.
