### ISSUE TITLE
Dirty version although there are no uncommited changes

### ISSUE THREAD

**Issue by eikaramba** [gladed/gradle-android-git-version#53]
We have the problem that since quite some time the versionname is always dirty. First i thought there are uncommited changes in our CI system, but even when building the apk locally i get the "-dirty" versionname. the git repo is clean see here:
![grafik](https://user-images.githubusercontent.com/1320525/45631913-59429380-ba9c-11e8-98e0-e18faa5443a5.png)

That's what i get after building or executing "gradle --quiet androidGitVersion":
![grafik](https://user-images.githubusercontent.com/1320525/45632053-bcccc100-ba9c-11e8-90ce-e610a40d1732.png)

do you any idea why that is happening? Is there something else i can have a look at or provide some other logs?

**Comment by eikaramba** [comment]
i saw that you don't do anything special [here](https://github.com/gladed/gradle-android-git-version/blob/master/src/main/groovy/com/gladed/gradle/androidgitversion/AndroidGitVersion.groovy#L211), that's why i'm confused myself of why that problem occurs.

**Comment by gladed** [comment]
That does seem odd. I don't know enough about your project to reproduce the issue, but perhaps an update to jgit might help (it's a few versions old now). I'll ping here when it's ready.

**Comment by gladed** [comment]
0.4.5 is published, please give it a try and see if the problem is fixed. If not, if you could point me at a dummy (or real) project that exhibits this behavior I can try to develop a workaround?

**Comment by eikaramba** [comment]
tried 0.4.5 no luck - like so often it seems it is a problem with our setup. i tried jgit for windows as described here: https://gist.github.com/oculushut/2413a93f311980f18910

then i was able to see that it detects some uncommited changes. git doesn't. it seems to be an issue with uppercase/lowercase in combination with windows maybe. I'm trying to resolve it now, but obviously this means it is not a problem of this library :)

**Comment by gladed** [comment]
I agree. https://www.midgetontoes.com/2014/10/17/maven-jgitflow-working-tree-has-uncommitted-changes/ might give you some clues. Thanks for letting us know about it anyway!

**Comment by gladed** [comment]
BTW: as a workaround you can disable "dirty" detection by customizing the [`format`](https://github.com/gladed/gradle-android-git-version#format-string). e.g.:

    format "%tag%%-count%%-commit%%-branch%"

**Comment by 1951FDG** [comment]
I also have this issue: [repo](https://github.com/1951FDG/openpyn-nordvpn-juiceSSH)

I applied the workaround, but I still don't know what causes the project to be marked as dirty. Is there some debugging or logging possible to determine what may be causing this?

**Comment by GladeDiviney** [comment]
We get the dirty report from jgit, so it may either be something on disk during the build, or it may be a problem with jgit. What OS is this on?

**Comment by 1951FDG** [comment]
Hi, I'm on macOS 10.11.6, using Android Studio 3.3

**Comment by 1951FDG** [comment]
Hi again, **fixed it**, I downloaded jgit.sh at https://www.eclipse.org/jgit/download/, and ran jgit.sh status and got:

```
Changes not staged for commit:

	deleted:    app/src/main/java/io/github/sdsstudios/nvidiagpumonitor/Controllers/BaseController.kt

Untracked files:

	app/src/main/java/io/github/sdsstudios/nvidiagpumonitor/controllers/BaseController.kt
```

Notice `Controllers` and `controllers`, jgit seems to be case sensitive compared to the system git `git version 2.19.1`

I did the following and committed the changes to fix the dirty status:

```
git rm -r --cached .
git add .
```

**Comment by gladed** [comment]
Nice troubleshooting there! Thank you.

I wonder if `git config core.ignorecase true` would have made a difference?
