### ISSUE TITLE
Format branch not showing up

### ISSUE THREAD

**Issue by fluxxion82** [gladed/gradle-android-git-version#59]
Having an issue with the branch name showing up. The last tag we have is `0.0.2_171`, the hide branches property looks like `hideBranches = [ 'master', 'feature/.*']`. I've had a few things as the tag pattern, but currently I've got it set to `tagPattern(/^[0-9]+.*_[0-9]*$/)`. At one point I was seeing the branch names, and in fact, if I go to a feature branch and remove the 'feature/*' part from the hide branches, the branch name will show up when I call `androidGitVersion.name()`, but if I'm on a branch called `internal`, or `develop` even,  the branch name is not showing up. Things seemed to be working fine with the tag pattern `/^[0-9]+.*/`, but the branch name disappeared suddenly so I'm not sure what is happening. I'll post my entire formatting section. Any insights would be appreciated.

```
androidGitVersion {
    baseCode 169
    codeFormat 'MNNPPP'
    format '%tag%%-branch%%.dirty%'
    hideBranches = [ 'master', 'feature/.*']
    tagPattern(/^[0-9]+.*_[0-9]*$/)
    untrackedIsDirty = false
}
```

**Comment by gladed** [comment]
Are there commits after the tag? For example:

```
git checkout master
git tag 0.0.2_171
git checkout -b internal
```

In this case the current commit is still `master` and so no branch will appear in the name.

**Comment by fluxxion82** [comment]
The steps have been
```
git checkout internal
git merge develop
git tag 0.0.2_171
```
So the commit the tag `0.0.2_171` points to is the merge of the `develop` branch. Since neither the `develop` branch nor the `internal` branch are hidden, I should see a branch name, right? However, `develop` should see a different tag than internal, is that correct too?

**Comment by gladed** [comment]
Ah, I understand now.

How the plugin works today: if an explicit tag is given, that tag *alone* is used to name the build. That's because, in git, the tag positively identifies the commit of origin. So adding things like "-branch" seemed like extra noise in this case.

Untagged commits correspond to what I call "intermediate versions". All of the rules for generating useful names apply only to these intermediate versions, where just a tag isn't enough to identify the corresponding commit. So the behavior you're seeing is as-expected.

If you always want your build name to show that it's internal-only you can make that part of the tag itself, e.g. "0.0.2_171_internal".

**Comment by fluxxion82** [comment]
I think I understand a little better, however, I don't think this is not the behavior I was hoping for. If I do the above but do `git tag 0.0.2_171_internal`, then when I check out another branch, the version name will be something like `0.0.2_171_internal-branch', which is confusing. I get that the explicit tag points to the commit of origin, but the name of it doesn't tell you anything that useful. I think to add things like "-branch" to the name of the build wouldn't be extra noise, especially since you give us the option to add these things.
I guess we'll probably do without branch names or think of something else.

**Comment by gladed** [comment]
Maybe we can find a way to make this use case work. Is _171 a build number or something? What is the tag for in this case?

**Comment by fluxxion82** [comment]
'_171' is the version code for the android app. It was the pattern we were using before trying to automate things and using your lib. We're open to changing the format...it's probably not necessary to include that number the way we have things working right now. I think we want the branch name though so we can tell better which play store test track the build is on, which is why we have a branch called `internal`.

**Comment by gladed** [comment]
Well, if you have different tags for each track, then it's simply a matter of putting the track in the tag and hiding the branch name.

When merging between branches things can get tricky though, with the wrong tag getting picked. I usually end up sticking a tag on the merge commit.
