### ISSUE TITLE
Release through maven

### ISSUE THREAD

**Issue by AllanWang** [gladed/gradle-android-git-version#60]
Since I define my versions in a separate module, I depend on the old `classpath` import.

From [maven](https://mvnrepository.com/artifact/gradle.plugin.com.gladed.gradle.androidgitversion/gradle-android-git-version), the last release is still at 0.4.7. Is there any chance it can get updated to include 0.4.9?

(May relate to my previous issue #46)

**Comment by gladed** [comment]
I'll look into it!

**Comment by gladed** [comment]
New releases are under a shorter name now:

https://mvnrepository.com/artifact/com.gladed.androidgitversion/gradle-android-git-version/0.4.9
