### ISSUE TITLE
Increment version code without changing version name

### ISSUE THREAD

**Issue by fluxxion82** [gladed/gradle-android-git-version#61]
Is there a good way to increment the version code but keeping the version name the same? I want to have one version, say `1.2.3` with version code 5, for our alpha users, and then when we promote the version to beta, I want the version to be the same, `1.2.3` but have the version code be 6 to satisfy the play store requirements. I'm not seeing a good way to set the `codeFormat` so that the version code gets incremented without something in the version name being incremented.
I was thinking of writing a gradle task to update the `baseCode` by reading the value from a version file and then saving the version file after updating the value. Ideally we wouldn't have to use a file for this and maybe there is a way to do it without it? We were originally using a version file to store the version name and code but went to your plugin to avoid doing that.
The tag format we use right now is `1.2.3_5`, and the tag pattern is `/^[0-9]+.*/`. I've tried to update the tagPattern to use just look at the last number(s), which is the version code that we increment when creating the tag, but haven't had any luck (I've been trying to update the `codeFormat` some as well).
Is it possible to do this or do we need to increment part of the version name?

**Comment by gladed** [comment]
You could use `BB` in `codeFormat` to insert the number of builds since the last matching tag, and use `tagPattern` to exclude tags containing `_`. That would give you 99 commits before rolling.

Otherwise, you'd need another feature I think. Maybe `R` for release # (essentially a fourth version code). But I would recommend just rolling the 3rd "patch" version number, since any outward facing release (even a beta) is really its own version.

**Comment by fluxxion82** [comment]
I set the `codeFormat` to be `BBB` and the `tagPattern` is set to `/(?!_[0-9]{1,9})^[0-9]+.[0-9]+.[0-9]+/`, which ignores everything after the `_` in the git tag we use, and I can see version code increment as you describe but the version name becomes `untagged`. Does the `tagPattern` use normal regex? Is it not understanding the negative lookahead maybe?

**Comment by gladed** [comment]
You're right, the version name would take on the intermediate form in that case. 

Also, `tagPattern` really only governs which tags to look at. It doesn't control which part of the tag to look for version numbers.

It really sounds like you want a fourth version number, eg 1.2.3.4. But this is outside of semver.org recommendations. Is there some reason you don't want to bump the patch number? (e.g. 1.2.3 = alpha1, 1.2.4 = beta1, 1.2.5 = FC)

**Comment by fluxxion82** [comment]
Ah, I see. 

Yeah, I personally agree with you that we should be bumping the patch number for every release since there are differences, although very minor, in the versions and they are their own version, as you mention, but I think having the same version name would make it easier to use a tool we have to track versions the way they want to, and I think our iOS team does something similar with using one 'version name', so there's some pressure to try and keep things more consistent with them I guess. I don't think it's a huge deal telling them we can't do this. I'll tell them that we'll have to bump the patch number for each release for now and hopefully they can find another way to track the releases in that tool. Having the recommendations from semver.org is good to have, so thanks to pointing to that. If it really comes down to it, we can maybe add a gradle task to help do what they want, but I think we'll be ok with bumping the version number.

If you happen to think of some way of adding a new feature or some way we can do things with the current setup that would help with doing the original request, I'll be watching the repo and can bring it up them if/when that happens. 

Thanks anyway and for the quick responses!

**Comment by gladed** [comment]
Thanks for the response! I actually think to support this use case it wouldn't be unreasonable to capture a number in the remainder of the version name, e.g. '2' in 1.3.4-beta2, and pack that into `codeFormat`as `R`. I'll keep this open as a request for that feature.

**Comment by gladed** [comment]
Released in `0.4.10`. But be aware: with `codeFormat` of `MNPR`, `1.3.2-alpha2` will get a code of 1322 and `1.3.2-beta1`will have a code of 1321. So you must use incrementing numbers with each release (alpha1, beta2, rc3), which is not intuitive, so I still recommend using semver (e.g. 1.3.2-alpha1, 1.3.3-beta1, 1.3.4-rc1)

**Comment by fluxxion82** [comment]
I've updated the plugin version and looks like we're able to do what we wanted now! Hopefully we only do this for our internal -> alpha versions and we use the recommended semver for the other versions, but this will help out for sure. Thanks so much!
