### ISSUE TITLE
Doesn't work with `git worktree`

### ISSUE THREAD

**Issue by wngr** [gladed/gradle-android-git-version#63]
If the repo is checked out using the `git worktree` feature, `name` comes back unknown:
```
androidGitVersion.name  unknown
androidGitVersion.code  0
```

Works well with the plain git repo, though.

Maybe this could be added as a caveat (or fixed ;-) )

**Comment by gladed** [comment]
Unfortunately, [jgit does not support worktree](https://git.eclipse.org/r/#/q/project:jgit/jgit+is:open+message:worktree) at this time, which limits what I can do. I'll add a note to the README.md.
