### ISSUE TITLE
Commit hash prefix length should be configurable

### ISSUE THREAD

**Issue by otopetrik** [gladed/gradle-android-git-version#64]
It is useful to generate *same* "version name" for projects sharing single git repository.
(e.g. an android gradle build and a maven build)

The problem is, that different plugins have different idea about the git hash prefix length:

- It looks like this plugin has the value *fixed* to 7 characters:
https://github.com/gladed/gradle-android-git-version/blob/8821de1447d605e64e090fa72c66d0f6f535bf35/src/main/groovy/com/gladed/androidgitversion/AndroidGitVersion.groovy#L207

- Another plugin (jgitver-maven-plugin) defaults to 8 characters, and the value is *configurable* ([**gitCommitIdLength**](
https://github.com/jgitver/jgitver-maven-plugin/blob/668b5612b2b7d83b8da72657407463e4e57d9c23/src/main/java/fr/brouillard/oss/jgitver/mojos/JGitverMojo.java#L48)). Unfortunately, it requires at least [8 characters](https://github.com/jgitver/jgitver/blob/de52d3b4a6546fd186702ad37b2554682e8c9a97/src/main/java/fr/brouillard/oss/jgitver/impl/GitVersionCalculatorImpl.java#L592).

- `git` itself also has a *configurable* value ([**core.abbrev**](https://git-scm.com/docs/git-config#Documentation/git-config.txt-coreabbrev)), but with minimum of 4 characters.

The ability to configure git hash prefix length for this plugin would make it possible to generate same version names for both projects.

**Comment by gladed** [comment]
That's a good idea. It should be configurable.

**Comment by gladed** [comment]
Try `commitHashLength` in 0.4.11.

**Comment by otopetrik** [comment]
Version 0.4.11 works great.
Thank you.
