### ISSUE TITLE
Generated version name is not a commit-ish (does not match output of git describe)

### ISSUE THREAD

**Issue by kworth** [gladed/gradle-android-git-version#66]
The output of git describe is useful because of how it enables one to run git commands with it and it is treated as a commit-ish. But the versionName generated by this plugin does not match the output of git describe. For instance,

```
$ git describe
0.6.2-1-g4a30b81

$ ./gradlew androidgitversion
0.6.2-1-4a30b81
```

Therefore, after running `./gradlew androidgitversion` and using the output in git commands, the result is similar to the following: 

```
$ git show 0.6.2-1-4a30b81
fatal: ambiguous argument '0.6.2-1-4a30b81': unknown revision or path not in the working tree.

$ git show 0.6.2-1-g4a30b81
commit 4a30b814eaddde78846a36e8419e005790f0e0be
...
```

Thus it becomes frustrating for the user to have to insert the 'g' in order to checkout and debug old versions, etc.

Thanks.

**Comment by GladeDiviney** [comment]
Can you modify `format` to get this effect?

`"%tag%%-count%%-gcommit%%-branch%%-dirty%"`

**Comment by kworth** [comment]
Yes, that does appear to work.
