### ISSUE TITLE
Describe output is empty?

### ISSUE THREAD

**Issue by 1951FDG** [gladed/gradle-android-git-version#80]
Hello,

I updated to v0.4.12 and tried changing my format to ```'%describe%%-branch%%-dirty%'``` but I get output `-slave-dirty`?

**Comment by gladed** [comment]
Can you show me the output from both `git describe` and `git describe --tags` at the command line?

**Comment by 1951FDG** [comment]
I get 1.0.3-617-g51de158 and 1.0.3-617-g51de158 respectively.

**Comment by gladed** [comment]
Looks like there was a problem with publishing. Please try again with `0.4.13`?

**Comment by 1951FDG** [comment]
`0.4.13` fixes the output!

**Comment by gladed** [comment]
Cool, thanks for the report, and sorry for the trouble!
