### ISSUE TITLE
[question] Support for incremental versionCode separately from versionName?

### ISSUE THREAD

**Issue by lfernandofaraujo** [gladed/gradle-android-git-version#84]
Is there a plan for support a incremental `versionCode` feature separately from `versionName`?

**Comment by gladed** [comment]
What are you looking for specifically? How would an incremental version code be calculated?

**Comment by lfernandofaraujo** [comment]
Sorry for don't pass any context for you.

I'm software developer at Brazil and the companies i've passed, the projects increase a versionCode manually and sequencial way. For example:

Release v1.0.0
|_ versionName: 1.0.0
|_ versionCode: 1

Release v1.1.0
|_ versionName: 1.1.0
|_ versionCode: 2

Release v1.1.1
|_ versionName: 1.1.1
|_ versionCode: 3

Release v1.2.0
|_ versionName: 1.2.0
|_ versionCode: 4

Release v1.3.0
|_ versionName: 1.3.0
|_ versionCode: 5

Is that possible?

**Comment by gladed** [comment]
Sometimes you have to go back and add v1.0.1 after labelling v1.1.0. What number does v1.0.1 get?

**Comment by lfernandofaraujo** [comment]
Oh you caught me 😆
I don't know. Exist a strategy for this? 👀

**Comment by gladed** [comment]
Well, you could abandon semver which may not make a ton of sense in Android anyway since upgrades for users is normally pretty linear. Version 1.486, version 1.487, ...

**Comment by lfernandofaraujo** [comment]
Thx @gladed
